### PR TITLE
People popup styling

### PR DESCRIPTION
**Pull request by ipd39952**
#### Notion Link
- [Notion Link](https://www.notion.so/lofftapp/aee7dc5e05e644a88521ee91e01a79a0?v=45b60a4d8a744d0ea17df8c98de771b3&p=1f9a8b90072e487ea488295c4ab171d5)

### Issues Ref
- #36 

### Assigned Devs
- @ipd39952 

### Changes and Updates
- Created PeoplePopup and Slider components
- Added mockup person object to people.js
- Merge with T-people-section branch

### Added APIs, Webpack or Yarn/NPM installs
- _No Added APIs_ 

### Notes
- PeoplePopup component requires detailed information from props (eg survey answers, social media links etc)
- TODO: Responsiveness

### CODE REVIEW

**Comment by jhibbeard89** [comment]
@ipd39952 awesome looks great, not sure if you haven't put in but just looking over the page I think it would be good that if you click on the background of the page it will close the modal and also when the cursor goes over the 'x' in the corner that it shows a clickable instead of pointer :)

**Comment by ipd39952** [comment]
@jhibbeard89 Great suggestions, should be implemented now :)

**Comment by jhibbeard89** [comment]
Awesome, :)

**Comment by valentinLW** [comment]
I adapted ivos popup slightly, so the people popup and the tag popup look and behave the same

**Comment by jhibbeard89** [comment]
Ah amazing, is it not ready, let me know can review later :)

**Review by jhibbeard89 — APPROVED** [review]
Amazing looks great :)I think we are going to discuss what to put under titles tonight.

**Pull request merged**
